USE final_project;

-- The OOPS Section
DROP TABLE IF EXISTS move_popularity;
DROP TABLE IF EXISTS item_popularity;
DROP TABLE IF EXISTS type_popularity;
DROP TABLE IF EXISTS pokemon_popularity;
DROP TABLE IF EXISTS wonder_trades;
DROP TABLE IF EXISTS pokemon;
DROP TABLE IF EXISTS teams;
DROP TABLE IF EXISTS natures;
DROP TABLE IF EXISTS items;
DROP TABLE IF EXISTS form_move;
DROP TABLE IF EXISTS moves;
DROP TABLE IF EXISTS images;
DROP TABLE IF EXISTS form_info;
DROP TABLE IF EXISTS forms;
DROP TABLE IF EXISTS hatching;
DROP TABLE IF EXISTS abilities;
DROP TABLE IF EXISTS species;
DROP TABLE IF EXISTS type_chart;
DROP TABLE IF EXISTS activity_log;
DROP TABLE IF EXISTS sessions;
DROP TABLE IF EXISTS user_auth;
DROP TABLE IF EXISTS users;
